apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: $(echo -n "${{ secrets.ROOT_PASSWORD }}" | base64)
  MYSQL_DATABASE: $(echo -n "${{ secrets.MYSQL_DB }}" | base64)
  MYSQL_USER: $(echo -n "${{ secrets.MYSQL_USER }}" | base64)
  MYSQL_PASSWORD: $(echo -n "${{ secrets.ROOT_PASSWORD }}" | base64)
  MYSQL_HOST: $(echo -n "${{ secrets.MYSQL_HOST }}" | base64)