apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: $(echo -n "password1" | base64)
  MYSQL_DB: $(echo -n "todos" | base64)
  MYSQL_USER: $(echo -n "root" | base64)  
  MYSQL_HOST: $(echo -n "mysql" | base64)