
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: rgnima/todo-list:latest
        ports:
        - containerPort: 3000
        env:    
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: ${{ secrets.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          value: "password1"
        - name: MYSQL_DB
          value: "todos" 
